events {
    worker_connections 1024;
}

http {
    upstream auth-service {
        server app1:8080;
    }

    upstream svc-a {
        server service-a:80;
    }

    upstream svc-b {
        server service-b:80;
    }

    server {
        listen 80;
        server_name localhost;

        add_header Access-Control-Allow-Origin  * always;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;

        if ($request_method = OPTIONS) {
            return 204;
        }

        location /register {
            proxy_pass http://auth-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /login {
            proxy_pass http://auth-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /verify {
            proxy_pass http://auth-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /users {
            proxy_pass http://auth-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /h2-console {
            proxy_pass http://auth-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location = /_validate {
            internal;
            proxy_pass              http://auth-service/auth/validate;
            proxy_pass_request_body off;
            proxy_set_header        Content-Length "";
            proxy_set_header        X-Original-URI $request_uri;
            proxy_set_header        Authorization  $http_authorization;
        }

        location /service-a {
            auth_request /_validate;
            proxy_pass http://svc-a/;
        }

        location /service-b {
            auth_request /_validate;
            proxy_pass http://svc-b/;
        }

        error_page 401 = @error401;
        location @error401 {
            default_type application/json;
            return 403 '{"error":"Acces refuse - token manquant ou invalide"}';
        }
    }
}